### ISSUE TITLE
Milestone For Initial Release

### ISSUE THREAD

**Issue by endlessdev** [endlessdev/android-cli#1]
- [x]  안드로이드 애플리케이션 파일 구조가 잘 이루어져 있는지 검사 필요
- [x]  안드로이드 패키지 목록 가져오기
  - [x] build.gradle 파일 읽어서 가져온 패키지 이름을 사용

**Comment by endlessdev** [comment]
웹팩 사용 및 리팩토링 이후에 차질이 생겨 몇가지 문제점 및 해결할 점에 대해 적어둡니다.
본 문제들이 해결되면 Initial Release 및 NPM 배포를 시작하겠습니다.

- [ ] 빌드 자동화 툴을 TravisCI 대신 CircleCI를 사용합니다.
- [ ]  안드로이드 애플리케이션 파일 구조가 잘 이루어져 있는지 검사 필요 (legacy problem)
- [ ]  사용하던 gradle-to-js 모듈이 작동하지 않으므로, 해당 라이브러리를 대체한 라이브러리나 새로운 대책을 만들어야 함.
- [ ]  boilerplates 폴더에 여러 탬플릿을 박아두고, 거기에서 가져와서 파일을 쓰는 방식이었는데, CLI 환경에선 boilerplate 폴더를 찾을 수 없다고 나옴. 해당 문제 확인해봐야 할 필요가 있습니다.
